chatApp/urls.py
from django.urls import path

from . import views

app_name = 'chatApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),

]

codenames/urls.py
from django.urls import path

from . import views

app_name = 'codenames'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),
]

loginPage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings
from . import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('loginApp.urls'), name='loginApp'),
    path('home/', include('smartHome.urls'), name='smartHome'),
    path('chat/', include('chatApp.urls'), name='chatApp'),
    path('codenames/', include('codenames.urls'), name='codenames'),
    path('', homepage.homepage, name='homepage')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codenames/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import random

chatrooms = {}

# Create your views here.


@login_required(login_url='/recipes/login?next=/codenames/')
def homepage(request):
    return render(request, 'codenames/home.html')


@login_required(login_url='/recipes/login?next=/codenames/')
def create_room(request):
    if request.method == 'GET':
        # room_id = random.randint(1000, 9999)
        room_id = 1111
        while room_id in chatrooms.keys():
            room_id = random.randint(1000, 9999)
        chatrooms[room_id] = 1

        print("A szoba azonositoja", room_id)
        return render(request, 'codenames/room.html', {"room_id": room_id})

    return render(request, 'codenames/home.html', {"error": 'Valami hiba tortent a szoba letrehozasanal!'})


@login_required(login_url='/recipes/login?next=/codenames/')
def join_room(request):
    if request.method == 'POST':
        join_code = request.POST.get('joinCode', None)

        if join_code:
            return render(request, 'codenames/room.html', {'room_id': join_code})


def exit_room(request):
    return redirect('/codenames')

templates/codenames/home.html
{% extends "loginApp/header.html" %}

{% block title %}Fokepernyo{% endblock %}

{% block content %}
{% if user.is_authenticated %}



    <h1>Hello {{ user.username }}</h1>
    <a href="{% url 'codenames:create_room' %}" class="btn btn-primary mb-3">Szoba letrehozasa</a>

    <form action="{% url 'codenames:join_room' %}" method="post">
    <div class="form-group">
        {% csrf_token %}
    <input id="joinCode" name="joinCode" class="form-control" type="number" size="4" placeholder="Room join code" />
    <input type="submit" class="btn btn-success mt-3" value="csatlakozas" />
    </div>

    </form>

{% endif %}

{% endblock %}

templates/codenames/map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>map</title>

    <Style>
        .main {
            height: 250px;
            width: 250px;
            background-color: black;
            border-radius: 15px;
            border: solid 4px #484030;
            position: absolute;
        }
        .civil{
            position: relative;
            display: inline-flex;
            top: 2px;
            left: 2px;
            margin-left: 5px;
            margin-top: 5px;
            height: 40px;
            width: 40px;
            border-radius: 3px;
            background-color: #d8cc98;
        }
        .red{
            position: relative;
            display: inline-flex;
            top: 2px;
            left: 2px;
            margin-left: 5px;
            margin-top: 5px;
            height: 40px;
            width: 40px;
            border-radius: 3px;
            background-image: radial-gradient(circle, rgba(234, 100, 77, 1) 10%, rgba(219, 54, 26, 1) 29%, rgba(243, 173, 160, 1) 32%, rgba(242, 114, 111, 1) 36%, rgba(234, 30, 46, 1) 100%);
        }

        .blue {
            position: relative;
            display: inline-flex;
            top: 2px;
            left: 2px;
            margin-left: 5px;
            margin-top: 5px;
            height: 40px;
            width: 40px;
            border-radius: 3px;
            background-image: radial-gradient(circle, rgba(95, 172, 250, 1) 10%, rgba(32, 75, 155, 1) 29%, rgba(48, 232, 241, 1) 32%, rgba(40, 169, 247, 1) 36%, rgba(0, 110, 150, 1) 100%);        }

        .killer {
            position: relative;
            display: inline-flex;
            top: 2px;
            left: 2px;
            margin-left: 5px;
            margin-top: 5px;
            height: 40px;
            width: 40px;
            border-radius: 3px;
            font-size: 30px;
            color: black;
            text-align: center;
            background-color: #303030;
        }

        .killer::after {
            position: absolute;
            content: "\2716";
            width: 100%;
            text-align: center;
            text-shadow: 0 0 5px white;
        }
    </Style>
</head>
<body>
    <div class="main">
        <div class="killer"></div>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="red"></div>
        <div class="civil"></div><br/>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="blue"></div>
        <div class="civil"></div>
        <div class="civil"></div><br/>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div><br/>
        <div class="civil"></div>
        <div class="killer"></div>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div><br/>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div>
        <div class="civil"></div>
    </div>
</body>
</html>

templates/codenames/wordCard.html
<div class='wordCard {{ class }}'><div class='textBox'><p class='cardText'>{{ word }}</p></div></div>