chatApp/urls.py
from django.urls import path

from . import views

app_name = 'chatApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),

]

codenames/urls.py
from django.urls import path

from . import views

app_name = 'codenames'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('create_room', views.create_room, name='create_room'),
    path('join_room', views.join_room, name='join_room'),
    path('exit_room', views.exit_room, name='exit_room'),
]

loginApp/urls.py
from django.urls import path

from . import views

app_name = 'loginApp'

urlpatterns = [
    path("", views.homepage, name='homepage'),
    path("register/", views.register_request, name='register'),
    path("login/", views.login_request, name='login'),
    path("logout/", views.logout_request, name='logout'),
    path("activation/",views.activation, name='activation'),
    path('permission/', views.permission_denied, name='permission'),
    path("allergies/", views.allergiesList, name="allergies"),
    path("allergies/new", views.add_allergie, name='add_allergie'),
    path("allergies/ajax/get_allergies_id", views.get_allergies_id, name='get_allergies_id'),
    path("allergies/<int:allergies_id>/view", views.view_allergie, name="allergies_view"),
    path("allergies/<int:allergies_id>/edit", views.update_allergie, name="allergies_edit"),
    path("allergies/<int:allergies_id>/delete", views.del_allergies, name="allergies_del"),
    path("categories/", views.categoryList, name='categories'),
    path("category/new", views.add_category, name="add_category"),
    path("category/ajax/get_category_id", views.get_category_id, name='get_category_id'),
    path("category/<int:category_id>/view", views.view_category, name='category_view'),
    path("category/<int:category_id>/edit", views.update_category, name="category_edit"),
    path("category/<int:category_id>/delete", views.del_category, name='category_del'),
    path("recipe_list/", views.recipe_list, name='recipes'),
    path("recipes/new", views.add_recipe, name='add_recipe'),
    path("recipes/<str:recipe_id>/view", views.view_recipe, name='recipe_view'),
    path("recipes/<str:recipe_id>/edit", views.update_recipe, name='recipe_edit'),
    path("recipes/<str:recipe_id>/pdf", views.recipe_to_pdf, name='recipe_pdf_generate'),
    path("recipes/<str:recipe_id>/delete", views.delete_recipe, name='recipe_delete'),
    path("ingredients/", views.ingredientList, name='categories'),
    path("ingredient/new", views.add_ingredient, name="add_ingredient"),
    path("ingredient/<int:ingredient_id>/view", views.view_ingredient, name='ingredient_view'),
    path("ingredient/<int:ingredient_id>/edit", views.update_ingredient, name="ingredient_edit"),
    path("ingredient/<int:ingredient_id>/delete", views.delete_ingredient, name='ingredient_del'),
    path("login_api/", views.save_api_call, name='login_api'),
    path("login_with_api/", views.api_login, name='login_with_api'),
    path("storage/", views.storage, name='storage')
]

loginPage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings
from . import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('loginApp.urls'), name='loginApp'),
    path('home/', include('smartHome.urls'), name='smartHome'),
    path('chat/', include('chatApp.urls'), name='chatApp'),
    path('codenames/', include('codenames.urls'), name='codenames'),
    path('', homepage.homepage, name='homepage')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartHome/urls.py
from django.urls import path

from . import views

app_name = 'smartHome'

urlpatterns = [
    path("index/", views.homepage, name='homepage'),
    path("ajax_switch/", views.ajax_switch, name='ajax_switch'),
]

templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'loginApp/css/default.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d750f44ba8.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>

    </title>
  </head>
 <body>
 <div class="container">
     <div class="text-center mt-3">
         <a href="{% url 'smartHome:homepage' %}"><i class="fas fa-home fa-10x"></i></a>
         <a href="{% url 'loginApp:recipes' %}"><i class="fas fa-book fa-10x"></i></a>
         <a href="{% url 'chatApp:homepage' %}"><i class="fas fa-comments fa-10x"></i></a>
         <a href="{% url 'codenames:homepage' %}"><i class="fas fa-user-secret fa-10x"></i></a>
     </div>
 </div>


  </body>
</html>